# Generated by Django 4.1.3 on 2023-02-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_remove_work_img_work_photo1_work_photo10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='square',
            field=models.CharField(max_length=70, null=True, verbose_name='Площадь'),
        ),
    ]
